#!/usr/bin/env fish
#
# An example hook script to verify what is about to be committed.
# Called by "git commit" with no arguments.  The hook should
# exit with non-zero status after issuing an appropriate message if
# it wants to stop the commit.
#
# To enable this hook, rename this file to "pre-commit".

if git rev-parse --verify HEAD >/dev/null 2>&1
	set against HEAD
else
	# Initial commit: diff against an empty tree object
	set against (git hash-object -t tree /dev/null)
end

for f in (git diff-index --cached --name-only --diff-filter=ACMR HEAD | grep "\.ipynb")
    jupyter-nbconvert --clear-output $f
    git add $f
end
exit 0
